### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by onny** [StarfishInteractive/norvos#10]
Hey,
in main directory of the project, I get following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project norvos: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```
I already tried several versions of openjdk/jre and the Oracle version of Java. All results in the same error :(

**Comment by connorlanigan** [comment]
This means that your maven setup is not using Java 8.
Try printing `JAVA_HOME` to see if it is set to the correct path of your Java 8 JDK.

**Comment by onny** [comment]
Cool thank you, this one seems to work: 
```
JAVA_HOME=/usr/lib/jvm/java-8-jdk mvn install
```
Now I get a different error:
```
TESTS:
Running de.norvos.i18n.TranslationsTest
[DEBUG] Missing translation resource: errors#registrationFailed
[DEBUG] Missing translation resource: this resource does#not exist
[DEBUG] Missing translation resource: errors#testEntry
[...]
Running de.norvos.axolotl.AxolotlStoreTest
[DEBUG] Missing translation resource: errors#databaseError
[CRITICAL] <I18N:errors.databaseError>
[...]
Failed tests:   translationAvailable(de.norvos.i18n.TranslationsTest): expected:<[Registration failed. Reason: TestReason]> but was:<[<I18N:errors.registrationFailed>]>
  test(de.norvos.account.AccountDataStoreTest): expected null, but was:<overwrittenTestString>
```

**Comment by connorlanigan** [comment]
The database test assumes that the application data directory is clean (which gets filled during the test), thus you have to remove `~/.norvos` before running the build again.
The missing translation bug occurs only sometimes, and can currently be fixed in Eclipse by executing `Project -> Clean...`.
