### ISSUE TITLE
Unifying output messages

### ISSUE THREAD

**Issue by connorlanigan** [StarfishInteractive/norvos#9]
# Currently
Debug messages are outputted via different methods (System.out.println and Errors.*). This leads to unclear code and makes it hard to deal with generated output.

# After fixing
These message output should be unified into a single output process, which includes outputting the Axolotl debug messages. A logging framework should be used here, to allow for different relevance levels of messages.

# Relevant Code
 - `de.norvos.log.Errors.[debug|warning|messaging](String)`
 - other code which contains `System.out` and `System.err`
 - `org.whispersystems.libaxolotl.logging.AxolotlLogger` should be implemented

**Comment by Ch3ck** [comment]
@connorlanigan  I see this project as a good candidate for the Jacobs Hack this year. I'll get our team setup and look at this issue. I've forked the repo. You should see my pull requests any time soon
